public enum PositionGroupCondition
{
    MUSTBE_ITEM_PAPER,
    MUSTBE_ITEM_GRIDSMALL,
    MUSTBE_ITEM_GRIDBIG,

    MUSTBE_ITEM_FISHFILLET,
    MUSTBE_ITEM_FISHSTICKS,
    MUSTBE_ITEM_CHIKENFILLET,
    MUSTBE_ITEM_CHIKENNUGGET,

    MUSTBE_ITEM_FRYERBASKET,
}