public enum MistakeType
{
    PRODURO_NOCHAO,
    PRODURO_CONTAMINADO,
    PRODURO_CRU,
    PRODURO_QUEIMADO,
    PRODUTO_FRIO,

    PRODUTO_MISTURADO_GRELHADOR,
    PRODUTO_MISTURADO_GAVETA, 
    PRODUTO_MISTURADO_FRITADEIRA, 
    PRODUTO_MISTURADO_CESTODEFRITAR,

    BIFE_SAL_SEM,
    BIFE_SAL_MUITO,
    BIFE_CRUSALGADO,
    BIFE_ORDEMERRADA,

    FRITO_MALESCORRIDO,
    FRITO_SALGADO,


    GRELHADOR_FRITO,
    GRELHADOR_SUJO,

    FRITADEIRA_NAOSUBMERSO,
    FRITADEIRA_DIRETAMENTENACUBA,
    FRITADEIRA_BIFENACUBA,
    FRITADEIRA_ITEMNACUBA,
    FRITADEIRA_NAOATIVOUTEMPORIZADOR,
    FRITADEIRA_NAOESCORREUOLEO,

    GAVETA_GRELHA_FALTA,
    GAVETA_GRELHA_ERRADA,
    GAVETA_PAPEL_PARAFRITOS,
    GAVETA_PAPEL_FALTA,
    GAVETA_PAPEL_MUITO,
    GAVETA_PAPEL_SUJO,


    ITEM_CONTAMINADO,

    REL_GAVETAPRODUTO,
    REL_PRODUTOSLOT,

    UHC_ORDEMERRADA,
    UHC_TEMPORIZADOR_NAOACIONADO,
    UHC_TEMPORIZADOR_INVALIDADO,


    RECEITA_ERRADA,
}
