public enum MistakeType
{
    GAVETA_PRODUTO_CONTAMINADO,
    GAVETA_PRODUTO_MISTURADO_LOTE,
    GAVETA_PRODUTO_CRU,
    GAVETA_PRODUTO_QUEIMADO,

    GAVETABIFE_PAPEL_MUITO,
    GAVETABIFE_PAPEL_REUTILIZADO,
    GAVETABIFE_PAPEL_SUJO,
    GAVETABIFE_PAPEL_FALTA,
    GAVETABIFE_BIFE_TIPOERRADO,
    GAVETABIFE_BIFE_SEMSAL,
    GAVETABIFE_FRITO,


    GRELHADOR_SUJO,
    GRELHADOR_PRODUTO_CONTAMINADO,
    GRELHADOR_PRODUTO_FRITO,
    GRELHADOR_PRODUTO_MISTURADO,
    GRELHADOR_ORDEMERRADA,







    PRODUTO_CONTAMINADO,
    PRODURO_NOCHAO,
    PRODURO_QUEIMADO,
    PRODUTO_FRIO,

    PRODUTO_MISTURADO_GAVETA, 
    PRODUTO_MISTURADO_FRITADEIRA, 
    PRODUTO_MISTURADO_CESTODEFRITAR,

    BIFE_MUITOSAL,
    BIFE_CRUSALGADO,

    FRITO_MALESCORRIDO,
    FRITO_SALGADO,



    FRITADEIRA_NAOSUBMERSO,
    FRITADEIRA_DIRETAMENTENACUBA,
    FRITADEIRA_BIFENACUBA,
    FRITADEIRA_ITEMNACUBA,
    FRITADEIRA_NAOATIVOUTEMPORIZADOR,
    FRITADEIRA_NAOESCORREUOLEO,

    GAVETA_GRELHA_FALTA,
    GAVETA_GRELHA_ERRADA,
    GAVETA_PAPEL_PARAFRITOS,


    ITEM_CONTAMINADO,

    REL_GAVETAPRODUTO,
    REL_PRODUTOSLOT,

    UHC_ORDEMERRADA,
    UHC_TEMPORIZADOR_NAOACIONADO,
    UHC_TEMPORIZADOR_INVALIDADO,


    RECEITA_ERRADA,
}
