public enum ItemType
{
    NONE,

    BEEF,
    BEEF_NORMAL,
    BEEF_VEGAN,

    FRIED,
    FRIED_FISH,
    FRIED_FISH_FILLET,
    FRIED_FISH_STICKS,
    FRIED_CHIKEN,
    FRIED_CHIKEN_FILLET,
    FRIED_CHIKEN_NUGGET,


    BOARD,
    BOARD_BEEF,
    BOARD_BEEFNORMAL,
    BOARD_BEEFVEGAN,
    BOARD_FRIED,
    BOARD_FISHFILLET,
    BOARD_FISHSTICKS,
    BOARD_CHIKENFILLET,
    BOARD_CHIKENNUGGET,

    BOARDINTERIOR,
    BOARDINTERIOR_PAPER,
    BOARDINTERIOR_GRID,
    BOARDINTERIOR_GRIDSMALL,
    BOARDINTERIOR_GRIDBIG,


    EQUIPMENT,
    EQUIPMENT_CLEANINGSPONGE,
    EQUIPMENT_FRYERBASKET,



    BOX,

    BREAD,
    BREAD_NORMAL,
    BREAD_SEEDS,
    BREAD_NOGLUTEN,
    BREAD_UPPER,
    BREAD_LOWER,
    BREAD_MIDLE,

    CHEESE,
    CHEESE_NORMAL,
    CHEESE_CHEDDAR,
    CHEESE_SOY,

    INGREDIENT,
    INGREDIENT_BACON,
    INGREDIENT_ONION,
    INGREDIENT_TOMATO,
    INGREDIENT_LETTUCE,
    INGREDIENT_PICKLE,

    SAUCE,
    SAUCE_KETCHUP,
    SAUCE_MAYONNAISE,
    SAUCE_MUSTARD,
}