public enum MistakeType
{
    PRODURO_QUEIMADO,
    PRODUTO_FRIO,
    PRODUTO_COMASMAOS,

    PRODUTOBIFE_CRUSALGADO,
    PRODUTOBIFE_MUITOSAL,

    PRODUTOFRITO_SALGADO,



    GAVETA_PRODUTO_CONTAMINADO,
    GAVETA_PRODUTO_MISTURADO_LOTE,
    GAVETA_PRODUTO_CRU,
    GAVETA_PRODUTO_QUEIMADO,

    GAVETABIFE_PAPEL_MUITO,
    GAVETABIFE_PAPEL_REUTILIZADO,
    GAVETABIFE_PAPEL_SUJO,
    GAVETABIFE_PAPEL_FALTA,
    GAVETABIFE_BIFE_TIPOERRADO,
    GAVETABIFE_BIFE_SEMSAL,
    GAVETABIFE_FRITO,

    GAVETAFRITO_GRELHA_SUJA,
    GAVETAFRITO_GRELHA_ERRADA,
    GAVETAFRITO_GRELHA_FALTA,
    GAVETAFRITO_PAPEL,
    GAVETAFRITO_BIFE,
    GAVETAFRITO_FRITO_TIPOERRADO,



    UHC_TEMPORIZADOR_NAOACIONADO,
    UHC_TEMPORIZADOR_INVALIDADO,
    UHC_GAVETA_TIPO,
    UHC_GAVETA_PRODUTO,
    UHC_ORDEMERRADA,

    GRELHADOR_SUJO,
    GRELHADOR_PRODUTO_CONTAMINADO,
    GRELHADOR_PRODUTO_FRITO,
    GRELHADOR_PRODUTO_MISTURADO,
    GRELHADOR_ORDEMERRADA,

    FRITADEIRA_CESTO_BIFE,
    FRITADEIRA_CESTO_PRODUTOMISTURADO_TIPO,
    FRITADEIRA_CESTO_PRODUTOMISTURADO_LOTE,
    FRITADEIRA_OLEO_BIFE,
    FRITADEIRA_OLEO_PRODUTOMISTURADO_TIPO,
    FRITADEIRA_OLEO_PRODUTOMISTURADO_LOTE,
    FRITADEIRA_OLEO_NAOESCORREU,
    FRITADEIRA_PRODUTO_NAOSUBMERSO,
    FRITADEIRA_PRODUTO_DIRETAMENTENACUBA,
    FRITADEIRA_ITEMERRADO_EQUIPAMENTO,
    FRITADEIRA_TEMPORIZADOR_INVALIDADO,
    //FRITADEIRA_TEMPORIZADOR_NAOATIVOU,

    BATCHER_COZINHOUAMAIS,


    PREPARADOR_FALTA_CAIXA,
    PREPARADOR_FALTA_PAO,
    PREPARADOR_FALTA_HAMBURGUER,
    PREPARADOR_FALTA_QUEIJO,


    PREPARADOR_MISTUROU_PAO,
    PREPARADOR_MISTUROU_MOLHOS,
    PREPARADOR_MISTUROU_CARNES,
    PREPARADOR_MISTUROU_QUEIJOS,

    PREPARADOR_ITEM_INVALIDO,






    PRODUTO_CONTAMINADO,
    PRODURO_NOCHAO,
    ITEM_CONTAMINADO,
    RECEITA_ERRADA,
}
